jupyterlab/jupyter-renderers

packages/geojson-extension/style/index.css
The `overflow: hidden;` directive was overridden by `.jp-OutputArea-output`'s `overflow-x: auto;`, resulting in an ugly horizontal scrollbar below the leaflet map that jumped around all the time when panning, as Leaflet loaded new tiles.
=> Hide horizontal scroll bar below Leaflet map

packages/plotly-extension/src/Plotly.d.ts, packages/plotly-extension/src/index.tsx, packages/plotly-extension/style/index.css
Closes https://github.com/jupyterlab/jupyter-renderers/issues/21
Resolves an issue with bundling plotly.js using webpack: https://github.com/plotly/plotly.js#building-plotlyjs-with-webpack
=> Use plotly.js browser script vs. npm module

packages/geojson-extension/src/index.tsx
Fixes an issue where geojson documents don’t render tiles until the pane has been resized
=> Fix geojson-extension document rendering

.travis.yml, packages/fasta-extension/src/index.ts, packages/geojson-extension/package.json, packages/geojson-extension/src/index.tsx, packages/plotly-extension/package.json, packages/plotly-extension/src/index.tsx
Without a `setTimeout` (of any timeout value), I’m observing that geojson outputs don’t invalidate size and as a result render only a portion of their tiles. Documents don’t have this issue. I don’t really understand why so this is a temporary fix until we understand what’s going on.
As a side note: The scroll wheel zoom logic is only necessary for outputs (vs. documents), but I don’t know how to detect whether the widget is being used within an output or document context.
=> Fix invalidate size in geojson outputs

packages/fasta-extension/package.json, packages/geojson-extension/package.json, packages/katex-extension/package.json, packages/plotly-extension/package.json, packages/vega3-extension/package.json
Eases discoverability of extensions on npm registry.
C.f. https://github.com/jupyterlab/jupyterlab/issues/3841.
=> Add standardized keyword for extension

packages/geojson-extension/src/index.tsx
The `trackResize` options makes leaflet react to global browser window resizes, which is not needed in the context of JupyterLab.
=> Disable trackResize option

packages/geojson-extension/src/index.tsx
Leaflet needs to know the size of the viewport in order to calculate the zoom level for displaying geojson content.
In order to resize gracefully, `fitBounds` needs to be called each time the size of the map is changed.
By moving the `fitBounds` call into `update` we can ensure that the geojson will always fit inside the viewport of the map.
Fixes #28
=> Fix polygon map bounds

packages/katex-extension/style/index.css
Another possible fix for #117. How about this @gnestor?
=> Specify height for KaTeX svg elements.

README.md, package.json, packages/mathjax3-extension/LICENSE, packages/mathjax3-extension/README.md, packages/mathjax3-extension/package.json, packages/mathjax3-extension/scripts/generate-css.js, packages/mathjax3-extension/src/index.ts, packages/mathjax3-extension/style/fonts.css, packages/mathjax3-extension/style/index.css, packages/mathjax3-extension/tsconfig.json, yarn.lock
Don't merge yet - this doesn't work yet.
=> Initial version of a MathJax 3 (prerelease) extension.

packages/katex-extension/style/index.css, packages/mathjax3-extension/style/index.css
Follow-up to jupyterlab/jupyterlab#5115
=> Left align math in cell outputs for KaTeX and MathJax3 extensions.

.travis.yml
We no longer need Firefox and selenium, since the browser check uses `puppeteer`.
=> Clean up travis build

packages/plotly-extension/src/index.ts
This PR is a fix for #158
It looks to me that after computing the png image, the `model.setData` call was treating
plotly's traces array (`data`) as if it were the bundle's `data` property (`model.data`).
This was causing a malformed bundle to be saved in the notebook, and causing only the image/png form to be restored on notebook load.
cc @gnestor
=> Fix JSON error when saving notebook with plotly figure

.travis.yml, package.json, packages/fasta-extension/package.json, packages/geojson-extension/package.json, packages/katex-extension/package.json, packages/mathjax3-extension/package.json, packages/plotly-extension/package.json, packages/vega2-extension/package.json, packages/vega3-extension/package.json, yarn.lock
See the commit messages for an idea of the commands I ran to update these:
```
update-dependency --lerna --minimal --regex '^@jupyterlab/' ^next
update-dependency --lerna typescript ~3.1.1
```
edit package.json to update the @types/react resolution
```
git clean -dfx
yarn install
yarn check
yarn-tools fix-duplicates yarn.lock > a
mv a yarn.lock
git clean -dfx
yarn install
```
=> Update for JupyterLab 0.35

packages/katex-extension/package.json, packages/katex-extension/schema/plugin.json, packages/katex-extension/src/autorender.ts, packages/katex-extension/src/index.ts
Add settings section to `katex-extension`.
For now, it contains just one entry, `macros`, a collection of custom  LaTeX macros.
Cheers
=> @jupyterlab/katex-extension. Add settings section.

packages/plotly-extension/src/index.ts
Related to https://github.com/plotly/plotly.py/pull/1281
This just accept a config object for plotly.js that can be passed by plotly.py or the user. 
Demo notebook: https://gist.github.com/gnestor/07f30edf28a8c3a88a01dfc748a8201a
=> plotly-extension: Accept config object in data

README.md
The command needs to be `jlpm run publish` vs. `jlpm publish`, otherwise yarn will get confused and throw a "Package marked as private, not publishing" error.
=> Update publishing docs

packages/mathjax3-extension/README.md, packages/mathjax3-extension/package.json, packages/mathjax3-extension/scripts/generate-css.js, packages/mathjax3-extension/src/index.ts, packages/mathjax3-extension/style/fonts.css, packages/mathjax3-extension/tsconfig.json, yarn.lock
We compile without noUnusedLocals because MathJax has lots of errors with it on. See https://github.com/mathjax/MathJax-src/issues/347 for an issue about that.
=> Update to MathJax 3.0 final

packages/geojson-extension/package.json
Among the packages in this repo, only the geojson extension had apputils pinned with `~`, so I assume it is set too restrictive by mistake.
```
>=2.1.0 <2.2.0       >=2.0.0 <2.1.0 @jupyterlab/apputils
JupyterLab           Extension      Package
Conflicting Dependencies:
ValueError: The extension "@jupyterlab/geojson-extension" does not yet support the current version of JupyterLab.
```
=> geojson: support JupyterLab 2.1.0

package.json, packages/fasta-extension/package.json, packages/geojson-extension/package.json, packages/katex-extension/package.json, packages/mathjax3-extension/package.json, packages/vega2-extension/package.json, packages/vega3-extension/package.json, yarn.lock
This updates the renderers to work in JLab 3 (and introduces the dependency upgrade script from jlab to make things easier).
I didn't move them to prebuilt extensions—that is a much, much larger change (involving creating python packages, etc.)
I manually tested the math renderers by disabling the builtin renderer and enabling them one at a time.
I clicked through the rest of the notebooks in this repo and things seemed to be okay.
=> Update for JLab 3

packages/mathjax3-extension/package.json, packages/mathjax3-extension/src/index.ts, packages/mathjax3-extension/style/fonts.css, yarn.lock
MathJax 3.1 now comes with a [safe mode](http://docs.mathjax.org/en/latest/options/safe.html). This updates and enables it.
=> Update to MathJax 3.1

packages/mathjax3-extension/src/index.ts
Building on comments from @dpvc (thanks!) at https://github.com/jupyterlab/jupyter-renderers/pull/236#issuecomment-776808718, this simplifies our rendering to call the built-in rendering pipeline.
=> Simplify mathjax calls to call the built-in rendering pipeline.

packages/fasta-extension/setup.py, packages/geojson-extension/setup.py, packages/katex-extension/setup.py, packages/mathjax3-extension/setup.py, packages/vega2-extension/setup.py, packages/vega3-extension/setup.py
Being a monorepo, `.git` is not in each package directory. Instead, we look for the PKG-INFO file that will be in a .tar.gz package, and reverse the logic of the check.
=> Update the auto-skipping in setup.py to look for PKG-INFO

package.json
Fixes #249 
Run the `clean:all` script before building the packages to make sure prod assets are correctly created.
=> Run clean:all script in build:py

packages/fasta-extension/setup.py, packages/geojson-extension/setup.py, packages/katex-extension/setup.py, packages/mathjax3-extension/setup.py, packages/vega2-extension/setup.py, packages/vega3-extension/setup.py
Other software may use these pkgs without the need for JupyterLab to be installed
=> Remove dependency to JupyterLab

packages/fasta-extension/package.json, packages/fasta-extension/src/index.ts, packages/fasta-extension/src/msa.d.ts, yarn.lock
Swap from the unmaintained [wilzbach/msa](https://github.com/wilzbach/msa) to a fork ([jupyterlab-contrib/msa](https://github.com/jupyterlab-contrib/msa)) with bugfixes.
This fixes issues with the MSA visualiser not displaying in new browsers.
I've also reverted the `bio.io` dependency for `msa` to `v1.0.6` (https://github.com/jupyterlab-contrib/msa/commit/1d353efa5b59a94dc1edb14c97ecdfe9abfc99d8), which misses the latest `clustal` patches (https://github.com/wilzbach/bio.io/commit/233c569a000b4e481bc682dc1c5024aaa8f4c3b6).  
These were not included in the latest NPM build for `msa`, but might be worth later incorporating.
For this we'll need to fork `bio.io` too.
Hopefully everything is up to scratch!
Closes #258.
=> fix: swap to @jlab-contrib/msa

packages/mathjax3-extension/package.json, packages/mathjax3-extension/schema/plugin.json, packages/mathjax3-extension/src/index.ts, yarn.lock
* Add require package.
* Update mathjax to latest 3.2.2.
This PR is primarily to add the require command so one can import the physics package only if needed. 
So the following:
now renders as:
Also add some menu items to allow scaling / resetting scale and copying markdown to clipboard.
And here's how the 1.5 scale vs normal scale looks like:
Apologies in advance if I've missed something important as typescript is not my forte. Admittedly, some of these changes might need additional work to make robust. Happy for suggestions.
=> Refresh mathjax and add require package
