packages/geojson-extension/package.json, packages/geojson-extension/src/index.tsx, packages/json-extension/package.json, packages/json-extension/src/index.tsx, packages/plotly-extension/package.json, packages/plotly-extension/src/index.tsx
Note that these new file types can also supply icons now using `iconClass`.
=> Update for JLab 26

lerna.json, package-lock.json, packages/plotly-extension/package.json, packages/plotly-extension/src/index.tsx
Waiting on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18392
Closes https://github.com/jupyterlab/jupyter-renderers/issues/10
=> Import "plotly.js/lib/core"

packages/geojson-extension/package.json, packages/json-extension/package.json, packages/plotly-extension/package.json
Closes https://github.com/jupyterlab/jupyter-renderers/issues/19
=> Downgrade typescript from ~2.4.1 to ~2.3.1

README.md
I was wondering why I ran into #19 even though it was marked as fixed in this repo...
=> Update git URL in README.md

packages/geojson-extension/src/index.tsx
Closes https://github.com/jupyterlab/jupyter-renderers/issues/29
=> Enable/disable scroll on leaflet maps depending on focus/blue state

packages/geojson-extension/src/index.tsx
Fixes issue described in https://github.com/jupyterlab/jupyter-renderers/issues/28#issuecomment-332333159
=> Fix partial rendering of leaflet tiles

packages/plotly-extension/README.md, packages/plotly-extension/src/index.tsx, packages/plotly-extension/style/index.css
Closes https://github.com/jupyterlab/jupyter-renderers/issues/38
Test notebook: https://gist.github.com/gnestor/661f4b4a631ad810b377a911398d8753
=> Allow plotly.js to set its own height

package.json
This way I can develop without installing lerna globally.
=> Add watch to npm

.travis.yml
Links all of the extensions and runs a live JupyterLab instance, checking for JS console errors.  :boom:
=> Add a travis test

packages/geojson-extension/package.json, packages/json-extension/package.json, packages/katex-extension/package.json, packages/plotly-extension/package.json, packages/vdom-extension/package.json
cf https://github.com/jupyterlab/jupyterlab/issues/3145
=> Add prepack scripts

packages/plotly-extension/src/index.tsx
Closes https://github.com/jupyterlab/jupyter-renderers/issues/66
=> Add back plotly resize

notebooks/vega3-extension.ipynb
Also use the correct function in the notebook.
=> Use the correct MIME type `application/vnd.vegalite.v2+json`

packages/plotly-extension/style/index.css
Closes https://github.com/jupyterlab/jupyter-renderers/issues/85
=> Fix plotly height

packages/katex-extension/package.json, yarn.lock
We shouldn't merge until they release, but this is a potential fix for the MacOS rendering bug for fractions.
cc @gnestor @ellisonbg
=> [WIP] Bump KaTeX version.

README.md, packages/fasta-extension/README.md, packages/geojson-extension/README.md, packages/katex-extension/README.md, packages/plotly-extension/README.md, packages/vega2-extension/README.md
Continuation of https://github.com/jupyterlab/jupyter-renderers/pull/111
=> Use jlpm vs. yarn in READMEs

packages/fasta-extension/package.json, packages/geojson-extension/package.json, packages/katex-extension/package.json, packages/plotly-extension/package.json, packages/vega2-extension/package.json, yarn.lock
Fixes https://travis-ci.org/jupyterlab/jupyter-renderers/builds/365703952?utm_source=email&utm_medium=notification
=> Upgrade to jupyterlab 0.32

packages/fasta-extension/tsconfig.json, packages/geojson-extension/tsconfig.json, packages/katex-extension/tsconfig.json, packages/plotly-extension/tsconfig.json, packages/vega2-extension/tsconfig.json
Related to https://github.com/jupyterlab/jupyterlab/pull/4462/files
=> Target Typescript compilation to ES2015

packages/fasta-extension/tsconfig.json, packages/geojson-extension/tsconfig.json, packages/katex-extension/tsconfig.json, packages/plotly-extension/tsconfig.json, packages/vega2-extension/tsconfig.json
Fixes changes introduced by https://github.com/jupyterlab/jupyter-renderers/pull/137
=> Fix "outDir" value in tsconfig.json files

packages/fasta-extension/tsconfig.json, packages/geojson-extension/tsconfig.json, packages/katex-extension/tsconfig.json, packages/mathjax3-extension/tsconfig.json, packages/plotly-extension/tsconfig.json, packages/vega2-extension/tsconfig.json, packages/vega3-extension/tsconfig.json
This option lets typescript know where the source root is.
=> Add rootDir in tsconfig

packages/plotly-extension/src/index.ts
Closes https://github.com/jupyterlab/jupyterlab/issues/5890
=> Use Plotly.react vs. Plotly.newPlot

packages/fasta-extension/src/index.ts, packages/fasta-extension/style/msa.css
This fixes the webpack build and our CI:
```
ERROR in ./node_modules/msa/css/msa.css (./node_modules/css-loader/dist/cjs.js!./node_modules/msa/css/msa.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError
(52:8) Unknown word
50 | 
51 | .biojs_msa_labelblock::-webkit-scrollbar, .biojs_msa_rheader::-webkit-scrollbar{
> 52 |     // FIX scrollbars on Mac
|        ^
53 |     -webkit-appearance: none;
54 |     width: 7px;
```
=> Fix build issue caused by JS comment in msa CSS

packages/vega4-extension/src/index.ts
Fixes https://github.com/jupyterlab/jupyterlab/issues/6403
=> Add extension number for Vega package

.travis.yml
=> updated CI

packages/geojson-extension/package.json, packages/geojson-extension/src/index.ts
=> Add popup displaying geojson properties on click

packages/katex-extension/package.json, yarn.lock
Update Katex to its latest version
=> Update Katex to its latest version

packages/geojson-extension/style/base.css, packages/geojson-extension/style/index.css, packages/katex-extension/style/base.css, packages/katex-extension/style/index.css, packages/mathjax3-extension/style/base.css, packages/mathjax3-extension/style/index.css, packages/vega2-extension/style/index.css, packages/vega3-extension/style/base.css
Basically, move all in-plugin styling to base.css, which both index.css and index.js import.
=> Fix styling for plugins.

RELEASE.md, packages/vega2-extension/style/base.css, packages/vega3-extension/style/index.css
This follows up on #246 with a few more CSS fixes
=> More CSS fixes

package.json, yarn.lock
Minor maintenance PR to update `lerna` to version 4.
=> Update to `lerna` 4

packages/geojson-extension/src/index.ts
=> Use the provided sanitizer not the default one
